import type { AeorankNuxtConfig } from "./types.js";

const AI_CRAWLERS = ["GPTBot", "ClaudeBot", "PerplexityBot", "Google-Extended"];

function escapeHtml(text: string): string {
	return text
		.replace(/&/g, "&amp;")
		.replace(/</g, "&lt;")
		.replace(/>/g, "&gt;")
		.replace(/"/g, "&quot;");
}

function escapeXml(text: string): string {
	return text
		.replace(/&/g, "&amp;")
		.replace(/</g, "&lt;")
		.replace(/>/g, "&gt;")
		.replace(/"/g, "&quot;")
		.replace(/'/g, "&apos;");
}

export function generateLlmsTxt(config: AeorankNuxtConfig): string {
	const lines: string[] = [];
	lines.push(`# ${config.siteName}`);
	lines.push("");
	lines.push(`> ${config.description}`);
	lines.push("");
	lines.push("## Links");
	lines.push("");
	lines.push(`- [Home](${config.siteUrl})`);
	lines.push("");
	return lines.join("\n");
}

export function generateLlmsFullTxt(config: AeorankNuxtConfig): string {
	const lines: string[] = [];
	lines.push(`# ${config.siteName}`);
	lines.push(`URL: ${config.siteUrl}`);
	lines.push("");
	lines.push(config.description);
	lines.push("");
	if (config.organization) {
		lines.push(`## Organization`);
		lines.push("");
		lines.push(`${config.organization.name} is the organization behind ${config.siteName}.`);
		if (config.organization.url) {
			lines.push(`Website: ${config.organization.url}`);
		}
		lines.push("");
	}
	if (config.faq && config.faq.length > 0) {
		lines.push("## FAQ");
		lines.push("");
		for (const qa of config.faq) {
			lines.push(`### ${qa.question}`);
			lines.push("");
			lines.push(qa.answer);
			lines.push("");
		}
	}
	return lines.join("\n");
}

export function generateClaudeMd(config: AeorankNuxtConfig): string {
	const lines: string[] = [];
	lines.push(`# ${config.siteName}`);
	lines.push("");
	lines.push("## Overview");
	lines.push("");
	lines.push(config.description);
	lines.push("");
	lines.push("## Tech Stack");
	lines.push("");
	lines.push("- **Framework:** Nuxt 3");
	lines.push(`- **URL:** ${config.siteUrl}`);
	if (config.organization) {
		lines.push(`- **Organization:** ${config.organization.name}`);
	}
	lines.push("");
	return lines.join("\n");
}

export function generateSchemaJson(config: AeorankNuxtConfig): string {
	const graph: object[] = [];

	const org: Record<string, unknown> = {
		"@type": "Organization",
		name: config.organization?.name || config.siteName,
		url: config.organization?.url || config.siteUrl,
	};
	if (config.organization?.logo) {
		org.logo = config.organization.logo;
	}
	graph.push(org);

	graph.push({
		"@type": "WebSite",
		name: config.siteName,
		url: config.siteUrl,
	});

	if (config.faq && config.faq.length > 0) {
		graph.push({
			"@type": "FAQPage",
			mainEntity: config.faq.map((qa) => ({
				"@type": "Question",
				name: qa.question,
				acceptedAnswer: {
					"@type": "Answer",
					text: qa.answer,
				},
			})),
		});
	}

	const schema = {
		"@context": "https://schema.org",
		"@graph": graph,
	};

	return `${JSON.stringify(schema, null, 2)}\n`;
}

export function generateRobotsPatch(_config: AeorankNuxtConfig): string {
	const lines: string[] = [];
	lines.push("# AEOrank Robots.txt Patch");
	lines.push("# Add these directives to your robots.txt to allow AI crawlers");
	lines.push("#");
	lines.push("# Generated by AEOrank (https://aeorank.dev)");
	lines.push("");

	for (const crawler of AI_CRAWLERS) {
		lines.push(`User-agent: ${crawler}`);
		lines.push("Allow: /");
		lines.push("");
	}

	return lines.join("\n");
}

export function generateFaqBlocks(config: AeorankNuxtConfig): string {
	if (!config.faq || config.faq.length === 0) {
		return `<!-- AEOrank: No FAQ content configured. Add faq entries to your aeorank config. -->
<div itemscope itemtype="https://schema.org/FAQPage">
  <!-- Example:
  <div itemscope itemprop="mainEntity" itemtype="https://schema.org/Question">
    <h3 itemprop="name">What is your product?</h3>
    <div itemscope itemprop="acceptedAnswer" itemtype="https://schema.org/Answer">
      <p itemprop="text">Our product helps you...</p>
    </div>
  </div>
  -->
</div>
`;
	}

	const lines: string[] = [];

	const schemaObj = {
		"@context": "https://schema.org",
		"@type": "FAQPage",
		mainEntity: config.faq.map((qa) => ({
			"@type": "Question",
			name: qa.question,
			acceptedAnswer: {
				"@type": "Answer",
				text: qa.answer,
			},
		})),
	};

	lines.push('<script type="application/ld+json">');
	lines.push(JSON.stringify(schemaObj, null, 2));
	lines.push("</script>");
	lines.push("");
	lines.push('<div itemscope itemtype="https://schema.org/FAQPage">');

	for (const qa of config.faq) {
		lines.push('  <div itemscope itemprop="mainEntity" itemtype="https://schema.org/Question">');
		lines.push(`    <h3 itemprop="name">${escapeHtml(qa.question)}</h3>`);
		lines.push(
			'    <div itemscope itemprop="acceptedAnswer" itemtype="https://schema.org/Answer">',
		);
		lines.push(`      <p itemprop="text">${escapeHtml(qa.answer)}</p>`);
		lines.push("    </div>");
		lines.push("  </div>");
	}

	lines.push("</div>");
	lines.push("");

	return lines.join("\n");
}

export function generateCitationAnchors(config: AeorankNuxtConfig): string {
	const lines: string[] = [];
	lines.push("<!-- AEOrank Citation Anchors -->");
	lines.push("<!-- Add id attributes to your headings for deep linking -->");
	lines.push("");

	if (config.faq && config.faq.length > 0) {
		for (const qa of config.faq) {
			const slug = qa.question
				.toLowerCase()
				.replace(/[^a-z0-9]+/g, "-")
				.replace(/^-|-$/g, "");
			lines.push(`<h3 id="${slug}">${escapeHtml(qa.question)}</h3>`);
			lines.push("");
		}
	} else {
		lines.push("<!-- No FAQ headings to generate anchors for. -->");
	}

	lines.push("");
	return lines.join("\n");
}

export function generateSitemapAi(config: AeorankNuxtConfig): string {
	const lines: string[] = [];
	lines.push('<?xml version="1.0" encoding="UTF-8"?>');
	lines.push(
		'<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:ai="https://aeorank.dev/sitemap-ai">',
	);
	lines.push("  <url>");
	lines.push(`    <loc>${escapeXml(config.siteUrl)}</loc>`);
	lines.push(`    <ai:summary>${escapeXml(config.description)}</ai:summary>`);
	lines.push("  </url>");
	lines.push("</urlset>");
	lines.push("");
	return lines.join("\n");
}

export type AeoFile = {
	path: string;
	content: string;
	contentType: string;
};

export function generateAllFiles(config: AeorankNuxtConfig): AeoFile[] {
	return [
		{ path: "/llms.txt", content: generateLlmsTxt(config), contentType: "text/plain; charset=utf-8" },
		{ path: "/llms-full.txt", content: generateLlmsFullTxt(config), contentType: "text/plain; charset=utf-8" },
		{ path: "/CLAUDE.md", content: generateClaudeMd(config), contentType: "text/markdown; charset=utf-8" },
		{ path: "/schema.json", content: generateSchemaJson(config), contentType: "application/json; charset=utf-8" },
		{ path: "/robots-patch.txt", content: generateRobotsPatch(config), contentType: "text/plain; charset=utf-8" },
		{ path: "/faq-blocks.html", content: generateFaqBlocks(config), contentType: "text/html; charset=utf-8" },
		{ path: "/citation-anchors.html", content: generateCitationAnchors(config), contentType: "text/html; charset=utf-8" },
		{ path: "/sitemap-ai.xml", content: generateSitemapAi(config), contentType: "application/xml; charset=utf-8" },
	];
}
