import { auth } from "@clerk/nextjs/server";
import { createServerSupabaseClient } from "@/lib/supabase";

interface DimensionScore {
	id: string;
	name: string;
	score: number;
	maxScore: number;
	weightPct: number;
	status: "pass" | "warn" | "fail";
	hint: string;
}

/**
 * GET /api/report/[siteId] — Generate a printable HTML report.
 * Users can save-as-PDF from their browser (Cmd+P → Save as PDF).
 */
export async function GET(
	_request: Request,
	{ params }: { params: Promise<{ siteId: string }> },
) {
	const { userId } = await auth();
	if (!userId) {
		return new Response("Unauthorized", { status: 401 });
	}

	const { siteId } = await params;
	const supabase = createServerSupabaseClient();

	const { data: site } = await supabase
		.from("sites")
		.select("url")
		.eq("id", siteId)
		.eq("user_id", userId)
		.single();

	if (!site) {
		return new Response("Site not found", { status: 404 });
	}

	const { data: scan } = await supabase
		.from("scans")
		.select("score, grade, dimensions, pages_scanned, duration_ms, scanned_at")
		.eq("site_id", siteId)
		.eq("user_id", userId)
		.eq("status", "complete")
		.order("scanned_at", { ascending: false })
		.limit(1)
		.maybeSingle();

	if (!scan) {
		return new Response("No completed scan", { status: 404 });
	}

	const dims = scan.dimensions as DimensionScore[];
	const date = new Date(scan.scanned_at as string).toLocaleDateString("en-US", {
		year: "numeric",
		month: "long",
		day: "numeric",
	});

	const scoreColor = (s: number) => (s >= 70 ? "#16a34a" : s >= 40 ? "#d97706" : "#dc2626");

	const dimRows = dims
		.map(
			(d) => `
		<tr>
			<td style="padding:8px 12px;font-weight:500">${d.name}</td>
			<td style="padding:8px 12px;text-align:center;font-weight:600;color:${scoreColor((d.score / d.maxScore) * 100)}">${d.score}/${d.maxScore}</td>
			<td style="padding:8px 12px;text-align:center"><span style="padding:2px 8px;border-radius:4px;font-size:11px;font-weight:600;background:${d.weightPct >= 5 ? "#fef2f2" : d.weightPct >= 3 ? "#fffbeb" : "#f0fdf4"};color:${d.weightPct >= 5 ? "#dc2626" : d.weightPct >= 3 ? "#d97706" : "#16a34a"}">${d.weightPct}%</span></td>
			<td style="padding:8px 12px;color:#6b7280;font-size:13px">${d.status !== "pass" ? d.hint : "Passing"}</td>
		</tr>`,
		)
		.join("");

	const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>AEOrank Report — ${site.url}</title>
<style>
	@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Space+Grotesk:wght@700&display=swap');
	* { margin: 0; padding: 0; box-sizing: border-box; }
	body { font-family: Inter, sans-serif; color: #1f2937; background: #fff; padding: 48px; max-width: 900px; margin: 0 auto; }
	@media print { body { padding: 24px; } }
	h1 { font-family: 'Space Grotesk', sans-serif; font-size: 28px; letter-spacing: -0.02em; }
	.meta { color: #6b7280; font-size: 14px; margin-top: 4px; }
	.score-box { display: flex; align-items: center; gap: 24px; margin: 32px 0; padding: 24px; border: 1px solid #e5e7eb; border-radius: 12px; }
	.score-num { font-family: 'Space Grotesk', sans-serif; font-size: 56px; font-weight: 700; line-height: 1; }
	.score-label { font-size: 13px; color: #6b7280; margin-top: 2px; }
	.grade { font-family: 'Space Grotesk', sans-serif; font-size: 40px; font-weight: 700; }
	table { width: 100%; border-collapse: collapse; font-size: 14px; margin-top: 24px; }
	thead th { text-align: left; padding: 8px 12px; font-size: 11px; text-transform: uppercase; letter-spacing: 0.05em; color: #6b7280; font-weight: 600; border-bottom: 2px solid #e5e7eb; }
	tbody tr { border-bottom: 1px solid #f3f4f6; }
	.footer { margin-top: 48px; padding-top: 16px; border-top: 1px solid #e5e7eb; font-size: 12px; color: #9ca3af; }
</style>
</head>
<body>
<h1>${site.url}</h1>
<p class="meta">AEOrank Report — ${date} — ${scan.pages_scanned} pages scanned in ${Math.round((scan.duration_ms as number) / 1000)}s</p>

<div class="score-box">
	<div>
		<div class="score-num" style="color:${scoreColor(scan.score as number)}">${scan.score}</div>
		<div class="score-label">out of 100</div>
	</div>
	<div style="width:1px;height:56px;background:#e5e7eb"></div>
	<div>
		<div class="grade" style="color:${scoreColor(scan.score as number)}">${scan.grade}</div>
		<div class="score-label">AEO grade</div>
	</div>
</div>

<h2 style="font-size:18px;font-weight:700;margin-top:32px">Dimension Breakdown</h2>
<table>
<thead>
	<tr>
		<th style="width:30%">Dimension</th>
		<th style="text-align:center;width:12%">Score</th>
		<th style="text-align:center;width:10%">Weight</th>
		<th>Recommendation</th>
	</tr>
</thead>
<tbody>${dimRows}</tbody>
</table>

<div class="footer">
	Generated by AEOrank — aeorank.dev
</div>
</body>
</html>`;

	return new Response(html, {
		headers: {
			"Content-Type": "text/html; charset=utf-8",
		},
	});
}
