export interface AeorankSvelteKitConfig {
	/** Display name for the site */
	siteName: string;
	/** Canonical URL of the site (e.g. "https://example.com") */
	siteUrl: string;
	/** Short description of the site */
	description: string;
	/** Organization info for JSON-LD schema */
	organization?: {
		name: string;
		url?: string;
		logo?: string;
	};
	/** FAQ entries to include in faq-blocks.html */
	faq?: Array<{ question: string; answer: string }>;
	/** Output directory for generated files (default: "static") */
	outputDir?: string;
}

/** The 8 AEO files generated by AEOrank */
export const AEO_FILES = [
	"llms.txt",
	"llms-full.txt",
	"CLAUDE.md",
	"schema.json",
	"robots-patch.txt",
	"faq-blocks.html",
	"citation-anchors.html",
	"sitemap-ai.xml",
] as const;

export type AeoFileName = (typeof AEO_FILES)[number];
