import type { AeorankAstroConfig } from "./types.js";

export interface GeneratedFile {
	name: string;
	content: string;
}

export function generateAllFiles(config: AeorankAstroConfig): GeneratedFile[] {
	return [
		{ name: "llms.txt", content: generateLlmsTxt(config) },
		{ name: "llms-full.txt", content: generateLlmsFullTxt(config) },
		{ name: "CLAUDE.md", content: generateClaudeMd(config) },
		{ name: "schema.json", content: generateSchemaJson(config) },
		{ name: "robots-patch.txt", content: generateRobotsPatch(config) },
		{ name: "faq-blocks.html", content: generateFaqBlocks(config) },
		{ name: "citation-anchors.html", content: generateCitationAnchors(config) },
		{ name: "sitemap-ai.xml", content: generateSitemapAi(config) },
	];
}

function generateLlmsTxt(config: AeorankAstroConfig): string {
	const lines: string[] = [];
	lines.push(`# ${config.siteName}`);
	lines.push("");
	lines.push(`> ${config.description}`);
	lines.push("");
	lines.push("## Main");
	lines.push("");
	lines.push(`- [${config.siteName}](${config.siteUrl}): ${config.description}`);
	lines.push("");
	return lines.join("\n");
}

function generateLlmsFullTxt(config: AeorankAstroConfig): string {
	const lines: string[] = [];
	lines.push(`# ${config.siteName}`);
	lines.push(`URL: ${config.siteUrl}`);
	lines.push("");
	lines.push(config.description);
	lines.push("");
	if (config.organization) {
		lines.push(`## Organization: ${config.organization.name}`);
		if (config.organization.url) {
			lines.push(`URL: ${config.organization.url}`);
		}
		lines.push("");
	}
	if (config.faq && config.faq.length > 0) {
		lines.push("## Frequently Asked Questions");
		lines.push("");
		for (const item of config.faq) {
			lines.push(`### ${item.question}`);
			lines.push("");
			lines.push(item.answer);
			lines.push("");
		}
	}
	return lines.join("\n");
}

function generateClaudeMd(config: AeorankAstroConfig): string {
	const lines: string[] = [];
	lines.push(`# ${config.siteName}`);
	lines.push("");
	lines.push("## Overview");
	lines.push("");
	lines.push(config.description);
	lines.push("");
	lines.push("## Tech Stack");
	lines.push("");
	lines.push("- **Framework:** Astro");
	lines.push(`- **URL:** ${config.siteUrl}`);
	lines.push("");
	if (config.organization) {
		lines.push("## Organization");
		lines.push("");
		lines.push(`- **Name:** ${config.organization.name}`);
		if (config.organization.url) {
			lines.push(`- **URL:** ${config.organization.url}`);
		}
		lines.push("");
	}
	return lines.join("\n");
}

function generateSchemaJson(config: AeorankAstroConfig): string {
	const graph: object[] = [];

	const org: Record<string, unknown> = {
		"@type": "Organization",
		name: config.organization?.name || config.siteName,
		url: config.organization?.url || config.siteUrl,
	};
	if (config.organization?.logo) {
		org.logo = config.organization.logo;
	}
	graph.push(org);

	graph.push({
		"@type": "WebSite",
		name: config.siteName,
		url: config.siteUrl,
	});

	if (config.faq && config.faq.length > 0) {
		graph.push({
			"@type": "FAQPage",
			mainEntity: config.faq.map((qa) => ({
				"@type": "Question",
				name: qa.question,
				acceptedAnswer: {
					"@type": "Answer",
					text: qa.answer,
				},
			})),
		});
	}

	const schema = {
		"@context": "https://schema.org",
		"@graph": graph,
	};

	return `${JSON.stringify(schema, null, 2)}\n`;
}

function generateRobotsPatch(config: AeorankAstroConfig): string {
	const crawlers = ["GPTBot", "ClaudeBot", "PerplexityBot", "Google-Extended"];
	const lines: string[] = [];

	lines.push("# AEOrank Robots.txt Patch");
	lines.push("# Add these directives to your robots.txt to allow AI crawlers");
	lines.push("#");
	lines.push(`# Generated by AEOrank for ${config.siteName}`);
	lines.push("");

	for (const crawler of crawlers) {
		lines.push(`User-agent: ${crawler}`);
		lines.push("Allow: /");
		lines.push("");
	}

	return lines.join("\n");
}

function escapeHtml(text: string): string {
	return text
		.replace(/&/g, "&amp;")
		.replace(/</g, "&lt;")
		.replace(/>/g, "&gt;")
		.replace(/"/g, "&quot;");
}

function generateFaqBlocks(config: AeorankAstroConfig): string {
	const faq = config.faq;

	if (!faq || faq.length === 0) {
		return `<!-- AEOrank: No FAQ content configured. Add faq items to your aeorank config. -->
<div itemscope itemtype="https://schema.org/FAQPage">
  <!-- Example:
  <div itemscope itemprop="mainEntity" itemtype="https://schema.org/Question">
    <h3 itemprop="name">What is your product?</h3>
    <div itemscope itemprop="acceptedAnswer" itemtype="https://schema.org/Answer">
      <p itemprop="text">Our product helps you...</p>
    </div>
  </div>
  -->
</div>
`;
	}

	const lines: string[] = [];

	const schemaObj = {
		"@context": "https://schema.org",
		"@type": "FAQPage",
		mainEntity: faq.map((qa) => ({
			"@type": "Question",
			name: qa.question,
			acceptedAnswer: {
				"@type": "Answer",
				text: qa.answer,
			},
		})),
	};

	lines.push('<script type="application/ld+json">');
	lines.push(JSON.stringify(schemaObj, null, 2));
	lines.push("</script>");
	lines.push("");

	lines.push('<div itemscope itemtype="https://schema.org/FAQPage">');
	for (const qa of faq) {
		lines.push('  <div itemscope itemprop="mainEntity" itemtype="https://schema.org/Question">');
		lines.push(`    <h3 itemprop="name">${escapeHtml(qa.question)}</h3>`);
		lines.push(
			'    <div itemscope itemprop="acceptedAnswer" itemtype="https://schema.org/Answer">',
		);
		lines.push(`      <p itemprop="text">${escapeHtml(qa.answer)}</p>`);
		lines.push("    </div>");
		lines.push("  </div>");
	}
	lines.push("</div>");
	lines.push("");

	return lines.join("\n");
}

function generateCitationAnchors(config: AeorankAstroConfig): string {
	const lines: string[] = [];

	lines.push("<!-- AEOrank Citation Anchors -->");
	lines.push("<!-- Add id attributes to your headings for deep linking -->");
	lines.push("");
	lines.push("<!-- Example usage: -->");
	lines.push(`<!-- <h2 id="about">${escapeHtml(config.siteName)} - About</h2> -->`);
	lines.push(
		`<!-- Deep link: ${config.siteUrl}/#about -->`,
	);
	lines.push("");

	return lines.join("\n");
}

function escapeXml(text: string): string {
	return text
		.replace(/&/g, "&amp;")
		.replace(/</g, "&lt;")
		.replace(/>/g, "&gt;")
		.replace(/"/g, "&quot;")
		.replace(/'/g, "&apos;");
}

function generateSitemapAi(config: AeorankAstroConfig): string {
	const lines: string[] = [];

	lines.push('<?xml version="1.0" encoding="UTF-8"?>');
	lines.push(
		'<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:ai="https://aeorank.dev/sitemap-ai">',
	);
	lines.push("  <url>");
	lines.push(`    <loc>${escapeXml(config.siteUrl)}</loc>`);
	lines.push(`    <lastmod>${new Date().toISOString().split("T")[0]}</lastmod>`);
	lines.push(`    <ai:summary>${escapeXml(config.description)}</ai:summary>`);
	lines.push("  </url>");
	lines.push("</urlset>");
	lines.push("");

	return lines.join("\n");
}
